title: What the facts!
description: Fun facts from lunch talks at VKI.

github_username: kreuzter

url: https://kreuzter.github.io
baseurl: /what-the-facts

permalink: pretty

theme: minima

collections:
  posts:
    output: true

liquid:
  error_mode: strict

strict_front_matter: true